### PR TITLE
Unpack bin format into Bytes instead of String

### PR DESCRIPTION
**Pull request by willhbr**
This allows for differentiating between messages that were encoded as a string or as binary, which is useful as binary messages may have invalid UTF-8 which shouldn't be allowed in strings. Bytes can still be turned into a string if the user wants to treat them the same, but I think this should be an explicit decision.

### CODE REVIEW

**Comment by kostya** [comment]
I prefer use strings, even for binary messages, until you have quite big reason, because it simplify things. Crystal allows binary strings, utf methods would just fails on it. If you real need to differentiating, you can extract this info from token. Also ruby msgpack gem packs strings just random as strings or binary (even for ascii strings), so i want my mappings/serializable code can correctly extract this (you removed this usage).

**Comment by willhbr** [comment]
My reasoning for this would be:

Strings are immutable, whereas Bytes can be mutated. Making a mutable Bytes object from a String requires a full copy to maintain the immutability guarantees of String.

You can still decode either String or Bytes into a (String | Bytes) union, which you can then turn into your preferred type. A helper function/type alias could be added here. `(String | Bytes).from_msgpack(...)` works as you'd expect.

If you're using the higher-level API (either using `MessagePack.unpack(..)` or `MessagePack::Any` from my [other PR](https://github.com/crystal-community/msgpack-crystal/pull/61) then you lose the string/bytes type information.

Ruby doesn't have a real bytes type, so I guess it makes sense for it to encode/decode into strings. Since Crystal has the bytes type, I would expect for binary messages to be turned into Bytes by default.

Would you accept this PR if the mapping/serialisable turned string or bytes into the type specified for the field?

**Comment by kostya** [comment]
Ok, i think we can add BytesT token, but `String.from_msgpack` and `Bytes.from_msgpack` should  load from StringT and BytesT tokens both. And user define what type to use.

Using unions not nice i think, because adds more code in mappings/serializable, need to think.

**Comment by willhbr** [comment]
I agree that using unions is messy. I'll re-work this to allow mappings to deserialise from either binary or strings.

**Comment by kostya** [comment]
Looks ok, thanks. Btw if you read bytes from StringT token, it create read-only slice, so you still can't modify it.

**Pull request merged**
