### PR TITLE
pack int and uint in the smallest size possible fixes #12

### LINKED ISSUE #12: different encoding ints
```
ruby -e 'require "msgpack"; p [1,2,3].to_msgpack.bytes'
[147, 1, 2, 3]
```

```
crystal eval 'require "./src/msgpack"; p [1,2,3].to_msgpack'
[147, 210, 0, 0, 0, 1, 210, 0, 0, 0, 2, 210, 0, 0, 0, 3]
```

much bigger.

### PR DESCRIPTION
**Pull request by benoist**
@kostya what do you think?

### CODE REVIEW

**Comment by kostya** [comment]
i think need to add pack, unpack benchmark with big array with mix of ints (small, big, negative)
and compare before after

and compare that byte size is equal to ruby

**Comment by benoist** [comment]
ruby

```
ruby bench/pack.rb
small string = 202000000, 0.951386
big string = 2000050000, 0.98031
hash string string = 158010000, 0.612735
hash string float64 = 159100000, 0.526743
array of strings = 78930000, 0.225795
array of floats = 540060000, 0.814733
array of mix int sizes = 200060000, 0.645044
Summary time: 4.76423
```

from master

```
crystal bench/pack.cr --release
small string = 202000000, 00:00:00.5280130
big string = 2000050000, 00:00:01.7760740
hash string string = 158010000, 00:00:00.3365180
hash string float64 = 159100000, 00:00:00.3603830
array of strings = 78930000, 00:00:00.1842520
array of floats = 540060000, 00:00:01.0552050
array of mix int sizes = 380060000, 00:00:00.8758160
Summary time: 00:00:05.1177890
```

from pack-small branch

```
crystal bench/pack.cr --release
small string = 202000000, 00:00:00.5209040
big string = 2000050000, 00:00:01.7304170
hash string string = 158010000, 00:00:00.3341170
hash string float64 = 159100000, 00:00:00.3527780
array of strings = 78930000, 00:00:00.1854080
array of floats = 540060000, 00:00:00.9413370
array of mix int sizes = 200060000, 00:00:00.9870250
Summary time: 00:00:05.0538190
```

Big size difference and a bit of a performance drop

**Comment by kostya** [comment]
is every branch in switch in `def write(value : Int8 | Int16 | Int32 | Int64 | UInt8 | UInt16 | UInt32 | UInt64)`
covered by spec? (seems it more than specs?)

**Comment by kostya** [comment]
also you using write_value(value.to_i8) for one byte, seems faster to use write_byte

**Comment by kostya** [comment]
`when (-0x20..0x7F)`
`when (0x00..0x7f)`
is not this is crossed regions? so second never happen?

**Pull request merged**
