### PR TITLE
support binary to avoid InvalidByteSequenceError

### PR DESCRIPTION
**Pull request by maiha**
When we unpack binary data that is not valid byte sequnce as UTF-8, it raises InvalidByteSequenceError.

This PR treats binary data as Slice(UInt8) rather than String as proposed in
https://github.com/msgpack/msgpack/blob/master/spec.md

``` shell
% echo -n "\xC4\x02\b\xE7" > binary.msgpack

# ruby
% ruby -r msgpack -e "p MessagePack.unpack(File.read('binary.msgpack')).bytes"
[8, 231]

# crystal (master)
% crystal eval 'require "./src/msgpack"; p MessagePack.unpack(File.open("binary.msgpack"))'
Invalid byte sequence in UTF-8 string (InvalidByteSequenceError)
[4430423] *CallStack::unwind:Array(Pointer(Void)) +87
...

# crystal (this PR)
% crystal eval 'require "./src/msgpack"; p MessagePack.unpack(File.open("binary.msgpack"))'
[8, 231]
```

Of course, packer works for binary too.

```
% crystal eval 'require "./src/msgpack"; STDOUT.write MessagePack.pack(Slice(UInt8).new(UInt8[0x08, 0xE7].to_unsafe, 2))' | hd
00000000  c4 02 08 e7                                       |....|
00000004
```

### CODE REVIEW

**Comment by kostya** [comment]
i think you missed add :BINARY to case in Unpacker#skip_value

**Comment by benoist** [comment]
Nice! Can you also add a binary benchmark?

**Comment by maiha** [comment]
Oh, thanks for `Unpacker#skip_value` issue. I completely forgot it!
Well, I found another bug too, so please wait for a while.

I'll also take benchmarks. thanks!

**Comment by maiha** [comment]
respected your comments, thanks!
- implement `Unpacker#skip_value` and `read_binary` macro
- fix binary with mapping (add test)
- add binary benchmarks

**Comment by kostya** [comment]
Seems Slice(UInt8)#to_msgpack also missing, or at least spec for it

**Comment by maiha** [comment]
`Slice(UInt8)#to_msgpack` has already been implmented as `Packer#write(Slice(UInt8)`.
But, the spec was missing as  kostya said. Thanks!

**Comment by benoist** [comment]
Thanks again :)

**Pull request merged**
