### PR TITLE
Pull parser

### PR DESCRIPTION
**Pull request by benoist**

### CODE REVIEW

**Comment by benoist** [comment]
@kostya

**Comment by benoist** [comment]
In order to support the socket problem from #19 I had to rewrite the unpacker, but this conflicted with the mapping as it requires to read the next token to check for nillable properties.

Have you got a better idea on how to go about that?

**Comment by kostya** [comment]
looks ok, but examples pack_unpack\* now failed to compile.

**Comment by kostya** [comment]
about mapping need to think more. may be split token reading on two parts, type and value.

**Comment by bebac** [comment]
The Unpacker looks good and it works as expected.

I am not sure, I understand why mappings can't use the Unpacker, but you know the code better than I do. It means this will not work either for the same reason the Unpacker did not work

```
require "socket"
require "msgpack"

class Person
  MessagePack.mapping({
    name: {type: String},
    age:  {type: Int32, nilable: true},
  })

  def initialize(@name : String, @age = nil : Int32?)
  end
end

TCPServer.open("::", 0) do |server|
  TCPSocket.open("::", server.addr.ip_port) do |client|
    sock = server.accept

    person = Person.new "Albert", 25
    client.write(person.to_msgpack)

    pull = MessagePack::PullParser.new(sock)
    p Person.new(pull)
  end
end

```

**Pull request merged**
